parameters:
    locale: 'en'
    enabled_locales: ['en', 'uk', 'es']

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Twig\ViteExtension:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $appEnv: '%kernel.environment%'
